export {
  shouldWrapExpression,
  isStaticExpression,
  isLiteralValue,
  wrapInGetter,
  isPropsAccess,
  isFunctionCall,
  isBinaryExpression,
  isConditionalExpression,
  isMemberExpression,
  isIdentifier,
  isTemplateLiteralWithExpressions,
  isLogicalExpression,
  isUnaryExpression,
} from '@liteforge/transform';
